# Base configuration for PGCM on CUB pretrained features
# CUB uses feature tensors and reconstructs those feature vectors.
dataset: "cubEMB"
model: "PGCM"

# Training Hyperparameters
epochs: 1500
batch_size: 128
num_workers: 0
lr: 0.001
warmup_epochs: 10
fixed_lr: False

# Model and Concept Embeddings
protosize: 64
embedding_size: 128
nb_proto: 350

# Loss Function Weights
lam_entropy: 0.025
lam_batch_entropy: 0.05
decay_lam_entropy: False
lam_reconstruction: 1.0
lam_kl: 0.00
lam_segmentation: 0.0
lam_orth: 0.0
lam_proto_emb: 1.0

# Settings
segmentation_method: "mask"
plot_frequency: 10
concepts_to_task: "thresholding"
use_weights: True
always_use_true_masks: False
use_initial_proto_embs: False
use_balanced_accuracy: True
use_linear_task_predictor: False

# Autoencoder Settings
use_pretrained_autoencoder: False
autoencoder_path: null

# Segmenter Settings
use_pretrained_segmenter: False
presegmented_datasets_path: null

# CUB dataset location
cub_dataset_root: null

# Interventions / Noise
intv_prob: 0.2
noisy_prob: 0.0
noisy_digit: null
noisy_target_digit: null
noisy_part: null
noisy_target_part: null
